services:
  django:
    build: .
    container_name: pythonbooks
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps:/app/apps
      - ./config:/app/config
      - ./manage.py:/app/manage.py
      - /app/.venv
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
