[tool:pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    --cov=apps/books/management
    --cov=apps/books/services
    --cov=apps/books/scrapers
    --cov-report=html
    --cov-report=term-missing
    --cov-fail-under=80
    --reuse-db
    --nomigrations