# Generated by Django 5.1.7 on 2025-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="electronic_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена электронной версии",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="url",
            field=models.URLField(blank=True, max_length=255, verbose_name="URL книги"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="website",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Сайт издательства"
            ),
        ),
    ]
