name: pythonbooks

on: [push, pull_request]

jobs:
  lint:
    name: ruff lint with fix
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v1

      - name: create virtual environment
        run: uv venv .venv

      - name: cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: install dependencies
        run: UV_VENV=.venv uv pip install -r requirements.txt

      - name: run ruff with --fix
        run: UV_VENV=.venv uv run -- ruff . --fix
