name: pythonbooks

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.11'
  UV_CACHE_DIR: ~/.cache/uv

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      uv-path: ${{ steps.setup-uv.outputs.uv-path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        id: setup-uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "uv-path=$HOME/.cargo/bin" >> $GITHUB_OUTPUT

  lint:
    needs: setup
    runs-on: ubuntu-latest
    env:
      PATH: ${{ needs.setup.outputs.uv-path }}:$PATH
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run ruff with autofix
        run: uv run ruff check pythonbooks --fix

  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      PATH: ${{ needs.setup.outputs.uv-path }}:$PATH
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ hashFiles('pythonbooks/requirements.txt') }}

      - name: Install dependencies from requirements.txt
        run: uv pip install -r pythonbooks/requirements.txt

      - name: Run tests
        run: uv run pytest pythonbooks

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "deploy"
