name: pythonbooks

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.11'
  UV_CACHE_DIR: ~/.cache/uv

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      uv-path: ${{ steps.setup-uv.outputs.uv-path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install uv
        id: setup-uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "uv-path=$HOME/.cargo/bin" >> $GITHUB_OUTPUT
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: verify uv installation
        run: |
          echo "UV path: ${{ needs.setup.outputs.uv-path }}"
          ls -la ${{ needs.setup.outputs.uv-path }}

      - name: install ruff
        run: ${{ needs.setup.outputs.uv-path }}/uv pip install ruff

      - name: run ruff
        run: ${{ needs.setup.outputs.uv-path }}/uv run ruff check .

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ hashFiles('**/pyproject.toml') }}

      - name: install dependencies
        run: ${{ needs.setup.outputs.uv-path }}/uv pip install pytest

      - name: run tests
        run: ${{ needs.setup.outputs.uv-path }}/uv run pytest

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "pass deploy"