name: pythonbooks

on: [push, pull_request]

jobs:
  lint:
    name: ruff lint with fix
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install uv
        run: pip install uv

      - name: install dependencies with uv
        run: uv pip install -r requirements.txt

      - name: install ruff
        run: uv pip install ruff

      - name: run ruff with autofix
        run: ruff check --fix .