name: pythonbooks

on: [push, pull_request]

jobs:
  lint:
    name: ruff lint with fix
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install ruff via uv
        run: |
          pip install uv
          uv venv .venv
          UV_VENV=.venv uv pip install ruff

      - name: run ruff
        run: UV_VENV=.venv uv run -- ruff format --check .