name: pythonbooks

on: [push, pull_request]

jobs:
  lint:
    name: ruff lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v1

      - name: install dependencies
        run: uv pip install -r requirements.txt

      - name: run ruff with --fix
        run: uv pip run ruff . --fix
